source("script.R")
png("plot3.png")
plot(data$Datetime, data$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="") 
lines(data$Datetime,data$Sub_metering_2,col="red")
lines(data$Datetime,data$Sub_metering_3,col="blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lwd=2, cex = 0.8)
#dev.copy(png,file="plot3.png")
dev.off()